apiVersion: apps/v1
kind: Deployment

metadata:
  name: javademoapp
  labels: 
     app: java-demo-app

spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-demo-app

  template:
    metadata:
      labels:
        app: java-demo-app
    spec:
      containers:
      - name: javademoapp
        image: jc02/javademoapp
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
