apiVersion: v1
kind: Service

metadata:
  name: javademoappservice
  labels:
    app: java-demo-app

spec:
  selector:
    app: java-demo-app
  ports:
    - port: 8081
      targetPort: 8080
  type: LoadBalancer
